{% set name = "csdms-hydrotrend" %}
{% set version = "3.0" %}
{% set build_string = environ.get('GIT_BUILD_STR', '') %}

package:
  name: {{ name }}
  version: {{ version }}

requirements:
  build:
    - bmi-babel
    - hydrotrend
  run:
    - bmi-babel
    - hydrotrend

test:
  requires:
    - pymt
