{% set name = "csdms-hydrotrend" %}
{% set version = "3.0" %}
{% set build_string = environ.get('GIT_BUILD_STR', '') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/mcflugen/hydrotrend
  git_branch: add-bmi-metadata

requirements:
  build:
    - bmi-babel
    - hydrotrend
  run:
    - bmi-babel
    - hydrotrend

test:
  requires:
    - pymt

about:
  home: http://csdms.colorado.edu/wiki/Model:HydroTrend
  license: MIT
  summary: Babelized version of hydrotrend
  description: |
    HydroTrend v.3.0 is a climate-driven hydrological water balance
    and transport model that simulates water discharge and sediment
    load at a river outlet.
  doc_url: http://csdms.colorado.edu/wiki/Model:HydroTrend
  dev_url: http://github.com/mcflugen/hydrotrend
