language: generic
os:
- linux
- osx
env:
  global:
  - THIS_PACKAGE="csdms-hydrotrend"
  - TRAVIS_PYTHON_VERSION="2.7"
  - NUMPY_VERSION="1.9"
  - secure: Uf+SdfNV/ui4EBdURYtDvHCWYX086cwyb12/S+KGZA6PHEuUYVrmzHqbYLWsQs2MCCGwk5H0RjAVxizGHbeq57Dqy8sAS0f/vEfbR/dX9XWT+/KiZ7Lo4cTHsZfHP+HR+1vIcRVTbtQvkdMpwScxMJzcUnESUXLyAP8TzNThIa5zsb1sN79hA2hooDSG0KibImyxz0d8P4FIvmPre/tt5JUrRIawV6jRgDQ7Xo0qT1/hqCKbc7vFZXSH6dgGteakmH6QuQr+1gX+eeYsg8/RXTeu+sTqmUo0faTZbbreW3JOJ+rIC1MDDjGHRUakfkrHG7AHc+Bu2ySHHZhsnJqP453Ix4O/rCZlM63qI7/8w2KT60ktII/NHSGvgv/p+GnLPtn4GL7+Zs96QsftYAgxWhXbt2QqMvnPBUaT0tFWIbA3V0ExxVWqP9NfmAcHJuR9Pv372c/U+L8jJyYiWigZkJybPP/3lOti9VAyl1BgGkEDhGLgg1GxltqVK2bT4F9FM5piMYr1zq8moepw09yhM+Mak3cqYiH/VcHJSJOIImRsk0P2FFbTUqNUx1mBoAq3RoWljDZ5T3+WO/XQlLYOF72Np8KAKiCI7d0qxCVgBj9WnDRMnjNuBb2BmXxeuz+bxGBBhnw7UNAfx77Zk7aSLapi63nNayMvL9D9ZUtH9IA=
sudo: false
install:
- bash ci/travis/install_python.sh $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
script:
- conda build recipe -c conda-forge -c csdms/channel/dev -c csdms
after_success:
- bash ci/travis/deploy_to_anaconda.sh $THIS_PACKAGE
